### ISSUE TITLE
Drawing the Tree

### ISSUE THREAD

**Issue by ajberlier** [KooroshNaderi/RT-RRT-Star#2]
https://dl.acm.org/doi/10.1145/2822013.2822036 

In the video here, you are drawing the tree in black as well as the set point and optimal path in the tree in red. I am not seeing where that is at in the code, could you please point out house to turn this feature on? Thank you!

**Comment by KooroshNaderi** [comment]
Hi, thanks for the question. You can find it in "find_best_path" function in "BallControl.cs" at Line 1318, and other colors you can search for the color-name in the code, e.g. Color.red.

**Comment by ajberlier** [comment]
I guess I should have been more clear, sorry. I see the Debug.DrawLine statements throughout, but when I run it does not display. Is there somewhere I need to toggle this on? Thank you!

**Comment by ajberlier** [comment]
Gizmos was disabled. I got it. Thank you!

**Comment by ajberlier** [comment]
Gizmos was disabled. I got it. Thank you!

**Comment by KooroshNaderi** [comment]
Thank you. Great that you figured it out.
